services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: credit_simulator
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  credit-simulator:
    image: credit-simulator
    container_name: creditas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/credit_simulator
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=mysecret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    external: true